// Code generated by "stringer -type=TokenCode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[ILLEGAL-1]
	_ = x[IDENT-2]
	_ = x[STRING-3]
	_ = x[NUMBER-4]
	_ = x[FLOAT-5]
	_ = x[DOT-6]
	_ = x[SEMICOLON-7]
	_ = x[DOUBLEQUOTE-8]
	_ = x[SINGLEQUOTE-9]
	_ = x[LPAREN-10]
	_ = x[RPAREN-11]
	_ = x[EQ-12]
	_ = x[PLUS-13]
	_ = x[MINUS-14]
	_ = x[MULTI-15]
	_ = x[BACKSLASH-16]
	_ = x[SLASH-17]
	_ = x[BINARY-18]
	_ = x[P2-19]
}

const _TokenCode_name = "EOFILLEGALIDENTSTRINGNUMBERFLOATDOTSEMICOLONDOUBLEQUOTESINGLEQUOTELPARENRPARENEQPLUSMINUSMULTIBACKSLASHSLASHBINARYP2"

var _TokenCode_index = [...]uint8{0, 3, 10, 15, 21, 27, 32, 35, 44, 55, 66, 72, 78, 80, 84, 89, 94, 103, 108, 114, 116}

func (i TokenCode) String() string {
	if i >= TokenCode(len(_TokenCode_index)-1) {
		return "TokenCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenCode_name[_TokenCode_index[i]:_TokenCode_index[i+1]]
}
