// Code generated by "stringer -type=TokenCode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[ILLEGAL-1]
	_ = x[NIL-2]
	_ = x[NEWLINE-3]
	_ = x[IDENT-4]
	_ = x[STRING-5]
	_ = x[NUMBER-6]
	_ = x[FLOAT-7]
	_ = x[DOT-8]
	_ = x[COMMA-9]
	_ = x[COLON-10]
	_ = x[SEMICOLON-11]
	_ = x[SINGLEQUOTE-12]
	_ = x[LPAREN-13]
	_ = x[RPAREN-14]
	_ = x[LBRACKET-15]
	_ = x[RBRACKET-16]
	_ = x[LBRACE-17]
	_ = x[RBRACE-18]
	_ = x[EQ-19]
	_ = x[PLUS-20]
	_ = x[MINUS-21]
	_ = x[MULTI-22]
	_ = x[BACKSLASH-23]
	_ = x[SLASH-24]
	_ = x[DOUBLESLASH-25]
	_ = x[COMMENT-26]
	_ = x[COMMENT_BLOCK-27]
	_ = x[BINARY-28]
	_ = x[KEY_MAIN-29]
	_ = x[KEY_FUNCTION-30]
	_ = x[KEY_LET-31]
	_ = x[KEY_STRUCT-32]
	_ = x[KEY_IMPL-33]
	_ = x[KEY_RANGE-34]
	_ = x[KEY_PANIC-35]
}

const _TokenCode_name = "EOFILLEGALNILNEWLINEIDENTSTRINGNUMBERFLOATDOTCOMMACOLONSEMICOLONSINGLEQUOTELPARENRPARENLBRACKETRBRACKETLBRACERBRACEEQPLUSMINUSMULTIBACKSLASHSLASHDOUBLESLASHCOMMENTCOMMENT_BLOCKBINARYKEY_MAINKEY_FUNCTIONKEY_LETKEY_STRUCTKEY_IMPLKEY_RANGEKEY_PANIC"

var _TokenCode_index = [...]uint8{0, 3, 10, 13, 20, 25, 31, 37, 42, 45, 50, 55, 64, 75, 81, 87, 95, 103, 109, 115, 117, 121, 126, 131, 140, 145, 156, 163, 176, 182, 190, 202, 209, 219, 227, 236, 245}

func (i TokenCode) String() string {
	if i >= TokenCode(len(_TokenCode_index)-1) {
		return "TokenCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenCode_name[_TokenCode_index[i]:_TokenCode_index[i+1]]
}
